import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { mockCloud, login, epubFixture, a } from "./helpers/cloud";

test("profile loads account collections lazily, saves identity, works offline, and isolates another account", async ({ page, context }, testInfo) => {
  const cloud = await mockCloud(page);
  cloud.setBookState({ favorite: true, status: "finished", profileOnly: true });
  await page.addInitScript(() => localStorage.setItem("autumn-language", "es"));
  await page.goto("/");
  await login(page);
  await expect(page.locator("#library-list .book-title")).toHaveCount(0);
  await page.locator('.nav-button[data-view="profile"]').click();
  await expect(page.locator("#profile-favorites .book-title")).toHaveText("Cloud EPUB");
  await expect(page.locator("#profile-finished")).toHaveCount(0);
  await expect(page.locator("#profile-completed-count")).toHaveText("1");
  await expect(page.locator("#profile-reading-count")).toHaveText("0");
  await expect(page.locator("#library-list .book-title")).toHaveText("Cloud EPUB");
  expect(cloud.downloads).toBe(0);
  expect(cloud.libraryQueries.some(query => query.includes("favorite=eq.true") && query.includes(`user_id=eq.${a}`))).toBeTruthy();
  expect(cloud.libraryQueries.some(query => query.includes("status=eq.finished") && query.includes(`user_id=eq.${a}`))).toBeFalsy();
  await page.locator("#profile-edit").click();
  await page.locator('#profile-form [name="display_name"]').fill("Facundo");
  await expect(page.locator('#profile-form [name="avatar_url"]')).toHaveCount(0);
  await page.locator('#profile-form [name="avatar"]').setInputFiles("src/assets/autumn-leaf.png");
  await expect(page.locator("#profile-form .avatar-preview")).toBeVisible();
  await page.locator('#profile-form [name="bio"]').fill("Leo historias para cada estación.");
  await page.locator('#profile-form button[type="submit"]').click();
  await expect(page.locator("#profile-editor")).toBeHidden();
  await expect(page.locator("#profile-name")).toHaveText("Facundo");
  await expect(page.locator("#profile-description")).toHaveText("Leo historias para cada estación.");
  await expect(page.locator("#profile-photo")).toBeVisible();
  expect(cloud.avatarUploads).toHaveLength(1);
  expect(cloud.avatarUploads[0].path).toBe(`${a}/avatar`);
  expect(cloud.avatarUploads[0].contentType).toBe("image/webp");
  expect(cloud.avatarUploads[0].size).toBeLessThanOrEqual(512 * 1024);
  expect(cloud.avatarUploads[0].size).toBeLessThan(readFileSync("src/assets/autumn-leaf.png").length);
  await expect.poll(() => page.locator("#profile-photo").evaluate((photo: HTMLImageElement) => photo.naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({path:testInfo.outputPath("profile.png"), fullPage:true});
  await page.reload();
  await expect(page.locator("#profile-name")).toHaveText("Facundo");
  await expect(page.locator("#profile-description")).toHaveText("Leo historias para cada estación.");
  await page.locator("#profile-favorites .book-title").click();
  await expect(page.locator(".epub-frame iframe")).toBeVisible();
  expect(cloud.downloads).toBe(1);
  await page.locator("#back-button").click();
  await expect(page.locator("#view-profile")).toBeVisible();
  await context.setOffline(true);
  await page.reload();
  await expect(page.locator("#profile-name")).toHaveText("Facundo");
  await expect(page.locator("#profile-favorites .book-title")).toHaveText("Cloud EPUB");
  await expect(page.locator("#profile-photo")).toBeVisible();
  await expect.poll(() => page.locator("#profile-photo").evaluate((photo:HTMLImageElement) => photo.naturalWidth)).toBeGreaterThan(0);
  await expect(page.locator("#profile-edit")).toBeDisabled();
  await page.locator("#profile-favorites .book-title").click();
  await expect(page.locator(".epub-frame iframe")).toBeVisible();
  expect(cloud.downloads).toBe(1);
  await context.setOffline(false);
  await page.locator('.nav-button[data-view="settings"]').click();
  await page.locator("#account-logout").click();
  await login(page,"b@example.org");
  await page.locator('.nav-button[data-view="profile"]').click();
  await expect(page.locator("#profile-username")).toHaveText("@reader_b");
  await expect(page.locator("#profile-favorites .book-title")).toHaveCount(0);
  await expect(page.locator("#profile-description")).not.toContainText("Leo historias");
  await expect(page.locator("#profile-photo")).toBeHidden();
});

test("local favorites and finished books appear in profile without cloud uploads", async ({page, context}) => {
  const cloud = await mockCloud(page,true);
  await page.addInitScript(() => localStorage.setItem("autumn-language", "es"));
  await page.goto("/");
  await login(page);
  await page.locator("#file-input").setInputFiles({name:"Local favorite.epub", mimeType:"application/epub+zip", buffer:await epubFixture()});
  await expect(page.locator(".epub-frame iframe")).toBeVisible();
  await page.locator("#back-button").click();
  await page.locator("#library-list .book-status").selectOption("finished");
  await expect(page.locator("#library-list .book-status")).toHaveValue("finished");
  await page.locator("#library-list .book-menu-options").getByRole("button", { name: "Favorito", includeHidden: true }).dispatchEvent("click");
  await page.locator('.nav-button[data-view="profile"]').click();
  await expect(page.locator("#profile-favorites .book-title")).toHaveText("Local favorite");
  await expect(page.locator("#profile-completed-count")).toHaveText("1");
  await context.setOffline(true);
  await expect(page.locator("#view-profile .book-status, #view-profile .favorite-button, #view-profile .book-cloud-button")).toHaveCount(0);
  await page.locator('.nav-button[data-view="library"]').click();
  await page.locator("#library-list .book-menu-options").getByRole("button", { name: "Quitar favorito", includeHidden: true }).dispatchEvent("click");
  await page.locator('.nav-button[data-view="profile"]').click();
  await expect(page.locator("#profile-favorites .book-title")).toHaveCount(0);
  await expect(page.locator("#profile-completed-count")).toHaveText("1");
  await page.reload();
  await expect(page.locator("#profile-favorites .book-title")).toHaveCount(0);
  await expect(page.locator("#profile-completed-count")).toHaveText("1");
  expect(cloud.uploads).toBe(0);
  expect(cloud.syncCount).toBe(0);
});

test("avatar picker rejects invalid files and retains edits after an upload failure", async ({page}, testInfo) => {
  const cloud = await mockCloud(page,true);
  await page.addInitScript(() => localStorage.setItem("autumn-language","es"));
  await page.goto("/"); await login(page);
  await page.locator('.nav-button[data-view="profile"]').click();
  await page.locator("#profile-edit").click();
  const file = page.locator('#profile-form [name="avatar"]');
  const submit = page.locator('#profile-form button[type="submit"]');
  await file.setInputFiles({name:"unsafe.svg",mimeType:"image/svg+xml",buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>')});
  await expect(page.locator('#profile-form [role="status"]')).toContainText("imagen JPG, PNG o WebP válida");
  await expect(submit).toBeDisabled();
  expect(cloud.avatarUploads).toHaveLength(0);
  await file.setInputFiles({name:"large.png",mimeType:"image/png",buffer:Buffer.alloc(10*1024*1024+1)});
  await expect(page.locator('#profile-form [role="status"]')).toContainText("menos de 10 MB");
  await page.locator("#profile-form .avatar-discard").click();
  await expect(submit).toBeEnabled();
  await file.setInputFiles({name:"spoof.png",mimeType:"image/png",buffer:Buffer.from("not an image")});
  await expect(submit).toBeDisabled();
  await expect(page.locator('#profile-form [role="status"]')).toContainText("imagen JPG, PNG o WebP válida");
  await file.setInputFiles("src/assets/autumn-leaf.png");
  await expect(page.locator("#profile-form .avatar-preview")).toBeVisible();
  await expect.poll(() => page.locator("#profile-form .avatar-preview").evaluate((image:HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
  await expect.poll(() => page.locator("#profile-form .avatar-preview").evaluate((image:HTMLImageElement) => image.naturalWidth)).toBeLessThanOrEqual(512);
  await page.screenshot({path:testInfo.outputPath("avatar-picker.png"),fullPage:true});
  await page.locator('#profile-form [name="display_name"]').fill("New name");
  cloud.avatarFailure = true;
  await submit.click();
  await expect(page.locator('#profile-form [role="status"]')).toContainText("No se pudo subir la foto");
  await expect(page.locator("#profile-editor")).toBeVisible();
  await expect(page.locator('#profile-form [name="display_name"]')).toHaveValue("New name");
  await expect(page.locator("#profile-name")).toHaveText("Reader");
  cloud.avatarFailure = false;
  await submit.click();
  await expect(page.locator("#profile-editor")).toBeHidden();
  await expect(page.locator("#profile-name")).toHaveText("New name");
  await expect(page.locator("#profile-photo")).toBeVisible();
  expect(cloud.avatarUploads).toHaveLength(1);
});

test("settings separate account, page, and interface and support keyboard navigation", async ({page}, testInfo) => {
  await mockCloud(page,true);
  await page.addInitScript(() => localStorage.setItem("autumn-language","es"));
  await page.goto("/");
  await login(page);
  await page.locator('.nav-button[data-view="settings"]').click();
  await expect(page.locator("#settings-account-panel")).toBeVisible();
  await expect(page.locator("#settings-account-panel #account-logout, #settings-account-panel #migrate-library")).toHaveCount(2);
  await expect(page.locator("#book-font")).toBeHidden();
  await expect(page.locator("#app-language")).toBeHidden();
  await page.screenshot({path:testInfo.outputPath("settings-account.png"), fullPage:true});
  await page.locator("#settings-page-tab").click();
  await expect(page.locator("#settings-page-panel #book-font")).toBeVisible();
  await expect(page.locator("#account-logout")).toBeHidden();
  await expect(page.locator("#app-language")).toBeHidden();
  await page.locator("#book-font").selectOption("georgia");
  expect(await page.evaluate(() => localStorage.getItem("autumn-book-font"))).toBe("georgia");
  await page.screenshot({path:testInfo.outputPath("settings-page.png"), fullPage:true});
  await page.locator("#settings-page-tab").focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.locator("#settings-interface-tab")).toHaveAttribute("aria-selected","true");
  await expect(page.locator("#settings-interface-panel #app-language")).toBeVisible();
  await expect(page.locator("#book-font")).toBeHidden();
  await expect(page.locator("#account-logout")).toBeHidden();
  await page.locator('[data-theme-choice="dark"]').click();
  expect(await page.evaluate(() => document.documentElement.dataset.theme)).toBe("dark");
  await page.screenshot({path:testInfo.outputPath("settings-interface.png"), fullPage:true});
  await page.locator("#settings-interface-tab").focus();
  await page.keyboard.press("Home");
  await expect(page.locator("#settings-account-tab")).toHaveAttribute("aria-selected","true");
  await expect(page.locator("#account-logout")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test("avatar uploads PNG when the WebView cannot encode WebP", async ({page,context}) => {
  const cloud = await mockCloud(page,true);
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.toBlob;
    HTMLCanvasElement.prototype.toBlob = function(callback, type, quality) {
      return original.call(this,callback,type === "image/webp" ? "image/png" : type,quality);
    };
  });
  await page.goto("/"); await login(page);
  await page.locator('.nav-button[data-view="profile"]').click();
  await page.locator("#profile-edit").click();
  await page.locator('#profile-form [name="avatar"]').setInputFiles("src/assets/autumn-leaf.png");
  await expect(page.locator("#profile-form .avatar-preview")).toBeVisible();
  await page.locator('#profile-form button[type="submit"]').click();
  await expect(page.locator("#profile-editor")).toBeHidden();
  expect(cloud.avatarUploads[0].contentType).toBe("image/png");
  expect(cloud.avatarUploads[0].size).toBeLessThanOrEqual(512*1024);
  await context.setOffline(true); await page.reload();
  await expect.poll(() => page.locator("#profile-photo").evaluate((image:HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
});
