import "fake-indexeddb/auto";
import { test, expect, vi } from "vitest";
import { folders } from "../../src/services/folders";
import { t } from "../../src/i18n";
import { localAll, localGet, localPut } from "../../src/services/local/database";
import { queued } from "../../src/services/sync/queue";
import type { StoredBook } from "../../src/storage";
const state = vi.hoisted(() => ({ ownerId: "owner-a", status: "expired" }));
vi.mock("../../src/services/auth", () => ({ auth: { state } }));
vi.stubGlobal("window", new EventTarget());
test("offline folder create/rename/move/delete is atomic, scoped, and preserves book bytes", async () => {
  const book: StoredBook = { id: "local-pdf", ownerId: "owner-a", name: "Test.pdf", format: "pdf", data: new Blob(["original"]), page: 187, cfi: null, fontSize: 100, addedAt: 1, lastOpenedAt: 1 };
  await localPut("books", book);
  const folder = await folders.create("Philosophy");
  await folders.move(book, folder.id);
  expect((await folders.snapshot()).memberships[0].folderId).toBe(folder.id);
  await folders.save({ ...folder, name: "University" });
  expect((await folders.snapshot()).folders[0].name).toBe("University");
  state.ownerId = "owner-b";
  expect((await folders.snapshot()).folders).toHaveLength(0);
  await expect(folders.move(book, folder.id)).rejects.toThrow();
  state.ownerId = "owner-a";
  await folders.save({ ...folder, deleted_at: new Date().toISOString() });
  expect((await folders.snapshot()).folders).toHaveLength(0);
  expect((await folders.snapshot()).memberships[0].folderId).toBeNull();
  const preserved = await localGet<StoredBook>("books", book.id);
  expect(preserved?.page).toBe(187); expect(await preserved?.data.text()).toBe("original");
  expect(await queued("owner-b")).toHaveLength(0);
  expect((await queued("owner-a"))[0].payload.deleted_at).not.toBeNull();
  expect(await localAll("books")).toHaveLength(1);
});
test("upload migration keeps folder assignment and coalesces cloud moves independently", async () => {
  const folder = await folders.create("Fiction");
  const book = { id: "fiction", ownerId: "owner-a", name: "Book.epub", format: "epub", data: new Blob(), page: 1, cfi: null, fontSize: 100, addedAt: 1, lastOpenedAt: 0 } satisfies StoredBook;
  await folders.move(book, folder.id);
  const clone = { ...book, id: "cloud-copy", ownerId: "owner-a", cloudId: "cloud-book" };
  await folders.migrateMembership(book, clone);
  expect((await queued("owner-a")).find(op => op.entity === "folder_book")?.payload.folder_id).toBe(folder.id);
  await folders.move(clone, null);
  const changes = (await queued("owner-a")).filter(op => op.entity === "folder_book");
  expect(changes).toHaveLength(1); expect(changes[0].payload.folder_id).toBeNull();
});
test("folder colour is durable offline, scoped to its owner and queued with renames", async () => {
  const folder = await folders.create("Colours", "#326fca");
  expect((await folders.snapshot()).folders.find(row => row.id === folder.id)?.color).toBe("#326fca");
  await folders.save({ ...folder, name: "Colours again", color: "#c84f90" });
  expect((await queued("owner-a")).find(op => op.entity === "folder" && op.entityId === folder.id)?.payload.color).toBe("#c84f90");
  state.ownerId = "owner-b";
  expect((await folders.snapshot()).folders.find(row => row.id === folder.id)).toBeUndefined();
  await expect(folders.save({ ...folder, color: "#0000ff" })).rejects.toThrow();
  state.ownerId = "owner-a";
  await expect(folders.save({ ...folder, color: "red;" })).rejects.toThrow(t("folderColorInvalid"));
  await folders.save({ ...folder, color: null });
  expect((await folders.snapshot()).folders.find(row => row.id === folder.id)?.color).toBeNull();
});
