import { test, expect, vi } from "vitest";
import { loadPagePreferences, savePagePreferences, defaultPagePreferences, pageSpacingCss, resolvePagePreferences, pagePreferencesEqual, saveBookPageOverrides, loadBookPageOverrides, columnCount } from "../../src/services/preferences/page";
test("page spacing persists, resets, validates, and produces EPUB typography rules", () => {
  const values = new Map<string, string>();
  vi.stubGlobal("localStorage", { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) });
  expect(loadPagePreferences()).toEqual(defaultPagePreferences);
  savePagePreferences({ ...defaultPagePreferences, lineHeight: 2, paragraphSpacing: 1.3 });
  expect(loadPagePreferences()).toEqual({ ...defaultPagePreferences, lineHeight: 2, paragraphSpacing: 1.3 });
  expect(pageSpacingCss(loadPagePreferences())).toContain("line-height: 2 !important");
  expect(pageSpacingCss(loadPagePreferences())).toContain("margin-block-end: 1.3em");
  expect(pageSpacingCss({ ...defaultPagePreferences, wordSpacing: .2, letterSpacing: -.03, textIndent: "custom", indentSize: 2 })).toContain("word-spacing: 0.2em");
  expect(pageSpacingCss({ ...defaultPagePreferences, wordSpacing: .2, letterSpacing: -.03, textIndent: "custom", indentSize: 2 })).toContain("letter-spacing: -0.03em");
  expect(pageSpacingCss({ ...defaultPagePreferences, wordSpacing: .2, letterSpacing: -.03, textIndent: "custom", indentSize: 2 })).toContain("text-indent: 2em");
  savePagePreferences({ ...defaultPagePreferences, lineHeight: Infinity, paragraphSpacing: -4 });
  expect(loadPagePreferences()).toEqual({ ...defaultPagePreferences, lineHeight: 1.6, paragraphSpacing: 0 });
  savePagePreferences({ ...defaultPagePreferences }); expect(loadPagePreferences()).toEqual(defaultPagePreferences);
  vi.unstubAllGlobals();
});
test("book overrides inherit individual global settings and remain local to owner and book", () => {
  const values = new Map<string, string>();
  vi.stubGlobal("localStorage", { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) });
  const global = { ...defaultPagePreferences, lineHeight: 1.8, font: "georgia" };
  saveBookPageOverrides("owner-a", "book-a", { lineHeight: 2.2, columns: "two" });
  expect(resolvePagePreferences(global, loadBookPageOverrides("owner-a", "book-a"))).toMatchObject({ lineHeight: 2.2, font: "georgia", columns: "two" });
  expect(loadBookPageOverrides("owner-b", "book-a")).toEqual({});
  expect(loadBookPageOverrides("owner-a", "book-b")).toEqual({});
  saveBookPageOverrides("owner-a", "book-a", { columns: "two" });
  expect(resolvePagePreferences(global, loadBookPageOverrides("owner-a", "book-a")).lineHeight).toBe(1.8);
  expect(columnCount("auto", 390, 844)).toBe(1);
  expect(columnCount("auto", 900, 500)).toBe(2);
  expect(columnCount("two", 390, 844)).toBe(1);
  expect(columnCount("two", 700, 400)).toBe(2);
  vi.unstubAllGlobals();
});
test("copying an inherited value into a book override is not an effective layout change", () => {
  const global = { ...defaultPagePreferences, lineHeight: 1.8, margins: "wide" as const, font: "georgia" };
  const inherited = resolvePagePreferences(global, {});
  const identicalOverrides = resolvePagePreferences(global, { lineHeight: 1.8, margins: "wide", font: "georgia" });
  const changedOverride = resolvePagePreferences(global, { lineHeight: 2.1 });
  expect(pagePreferencesEqual(inherited, identicalOverrides)).toBe(true);
  expect(pagePreferencesEqual(inherited, changedOverride)).toBe(false);
});
